### ISSUE TITLE
clock test fails

### ISSUE THREAD

**Issue by b2renger** [b2renger/PdDroidPublisher#9]
clock works fine on desktop but doesn't on android

**Comment by b2renger** [comment]
I copied the clock abs in the assets folder of the test, as I had an issue with the path.

The [declare -path ../../../pd-party/droidparty-abstractions] works on ubuntu, but as it seems not on android. Do I have to had something somewhere in the java code for the clock abs.

You can reproduce by simply removing the abs in the assets folder : openning the clockTest.pd file in desktop will succeed in creating the [clock] object, and android you'll get a complaint about the [clock] object not being found.

@mgsx-dev what do you think ?

**Comment by mgsx-dev** [comment]
obviously this can't work on android, the declare path only work with sources since folder doesn't exists on Android.

Only GUI Abstraction will work like this since it's not required on Android (it's implemented in Java code)

On another hand clock abstraction need to be included in Android apps some way : 
- included in assets folder
- or automatically copied in deployment folder (apps cache)

I think last solution is better but it's not implemented yet. So for now we have to copy clock abstraction in each assets folders.

**Comment by b2renger** [comment]
ok then assets folder it is for now.  

I think user will have a tendency to copy the specific droidparty abstraction (touch, taplist, loadsave) to their assets folder rather than keep it in their path anyway.

**Comment by b2renger** [comment]
new clock has been pushed according to the spec we decided.

It is still to be tested. As far as I've gone there seems to be an issue on android.

**Comment by mgsx-dev** [comment]
Clock is now almost fixed. The big issue was array function are not supported in current libpd version. I create a new ticket for that.
